<?php
//タイトル
$title = "新着情報";
//Composer
require_once __DIR__.'/vendor/autoload.php';
//.env
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();
//Header
include $_ENV['ROOT']."include/header.php";
?>
<!--本文-->
<div class="uk-container uk-margin-large<?= $style[0] ?> uk-animation-fade">
    <h1 class="uk-heading-bullet">新着情報</h1>
    <table class="uk-table uk-table-responsive uk-table-middle uk-table-divider uk-table-striped uk-table-hover">
        <thead>
        <tr>
            <th class="uk-width-small">日付</th>
            <th class="uk-width-medium">題目</th>
            <th class="uk-table-expand">内容</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>20/08/24</td>
            <td>歴史の意義を記述</td>
            <td>
                <ul>
                    <li>TOPICに『歴史の意義』ページを追加。ここに先日削除された思い入れを挿入しました。</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/22</td>
            <td>思い入れを削除</td>
            <td>
                <ul>
                    <li>題目が不気味だが、内容はトップページの最下部にあった私が古代史に興味を持った理由を記載していた部分を削除</li>
                    <li>もう少し分の体裁を整えたるにあたり、分量がものすごく多くなったので別ページで公開予定</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/19</td>
            <td>3つのトピックを追加</td>
            <td>
                <ul>
                    <li>百穴古墳群についてのトピックを追加</li>
                    <li>桐畑古墳群についてのトピックを追加</li>
                    <li>崇福寺跡についてのトピックを追加</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/17</td>
            <td>大伴遺跡</td>
            <td>
                <ul>
                    <li>大伴遺跡についてのトピックを追加</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/11</td>
            <td>日本語表記</td>
            <td>
                <ul>
                    <li>天気情報掲示テーブルの地区名が英語表記だった為、日本語表記に修正</li>
                    <li>天気情報処理部のコード整形。閲覧側に変更点なし</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/10</td>
            <td>史跡カバーの仕様変更</td>
            <td>
                <ul>
                    <li>従来では固定画像だったが、スライドショー式に変更。</li>
                    <li>現在は福王子古墳群ページに2枚のみスライドを実装</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/09</td>
            <td>大規模工事終了</td>
            <td>
                <ul>
                    <li>前日に続く大幅工事を終了</li>
                    <li>階層構造、ライブラリ構造を変更。閲覧側に変更点なし</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/08</td>
            <td>大規模工事開始</td>
            <td>
                <ul>
                    <li>サイトの構造変更に伴い一時的に公開停止</li>
                    <li>FirebaseCloudMessageを導入しようと試みたがことごとく失敗。実装は見送りとなった</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/02</td>
            <td>トラフィックの低減</td>
            <td>
                <ul>
                    <li>トップページのスライドショーのトラフィックが大きいと指摘を受け、従来より大幅に容量を削減</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/08/01</td>
            <td>追加調査</td>
            <td>
                <ul>
                    <li>調査場所を追加（石山地区、粟津/晴嵐地区、膳所地区）それに伴い、開発スケジュール（調査場所について）を更新した</li>
                    <li>大津市湖西はすべて調査することを決定した。</li>
                    <li>大津市湖東も史跡はあるが調査するか未定。</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/07/31</td>
            <td>セキュリティの更新</td>
            <td>
                <ul>
                    <li>バグ報告にApple製品(Webkitについて)の情報を追加</li>
                    <li>.htaccessの設定を更新</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/07/22</td>
            <td>開発スケジュールの見直し</td>
            <td>
                <ul>
                    <li>今後の開発スケジュールを更新</li>
                    <li>開発スケジュールレイアウトを予定、検討、中止の3つの分類に区分</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/07/17</td>
            <td>AndroidEdition削除</td>
            <td>
                <ul>
                    <li>Android版古代大津史アプリをGitHub上で公開していたが、使うメリットがあまりないので記事から削除</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/07/15</td>
            <td>天気情報</td>
            <td>
                <ul>
                    <li>トップページに現在の大津市各地の天気を表示する機能を追加</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/07/04</td>
            <td>注意喚起の削除</td>
            <td>
                <ul>
                    <li>6/13から表示を開始した注意喚起処理をトップページにバグトピックを掲載したため、削除</li>
                    <li>新着情報の掲載順を最新から古いの順番に変更</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/07/02</td>
            <td>問い合わせフォームを開発</td>
            <td>
                <ul>
                    <li>問い合わせフォームを開発</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/07/01</td>
            <td>バグトピック</td>
            <td>
                <ul>
                    <li>6月11日に発見した例のバグについての報告書をトップページに掲載。</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/29</td>
            <td>Android版アプリ公開</td>
            <td>
                <ul>
                    <li>
                        当サイト公式のAndroidアプリを公開しました。<br>
                        <a href="https://github.com/obakyuu/AncientOtsu_AndroidApp" target="_blank"
                           style="word-break: break-all">https://github.com/obakyuu/AncientOtsu_AndroidApp</a>
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/15</td>
            <td>Cookieの見直し</td>
            <td>
                <ul>
                    <li>最近臨時に作成したmobileクッキーの保存方法に誤りがあったので修正</li>
                    <li>史跡ページのレイアウトを変更するか検討</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/14</td>
            <td>再配置</td>
            <td>
                <ul>
                    <li>上記のナビバーにある「RUINS」と「TOPIC」の配置を逆に変更</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/13</td>
            <td>注意喚起</td>
            <td>
                <ul>
                    <li>
                        2日前に発見した不具合の修正方法がまだわからず、原因特定まで時間がかかると判断し、対象ユーザが閲覧した際に注意喚起が出る機能を臨時追加。
                        問題解決時にそれらの処理はすべて削除します。
                    </li>
                    <li>内部のファイル名を変更</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/12</td>
            <td>コード整形</td>
            <td>
                <ul>
                    <li>一部プログラム内のコードを修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/11</td>
            <td>GitHub</td>
            <td>
                <ul>
                    <li>
                        GitHubに当サイトのソースを公開しました。<br>
                        <a href="https://github.com/obakyuu/AncientOtsu" target="_blank"
                           style="word-break: break-all">https://github.com/obakyuu/AncientOtsu</a>
                    </li>
                    <li>Android版Chromeから当サイトを閲覧すると、一部のページでは正常にすべて表示されない不具合を発見。原因はわからず、Android版Firefoxから閲覧すると
                        問題なく閲覧ができたため、おそらくブラウザー側が原因の可能性がある。
                    </li>
                </ul>
            </td>
        </tr>
        <!--
        <tr>
            <td>20/06/10</td>
            <td>開設前の歴史</td>
            <td>4/29以前の出来事を記載したが、別に意味ない気がしたのでコメントアウトして
            隠蔽表示をした。そこまで見る物好きもいないでしょうし。</td>
        </tr>
        -->
        <tr>
            <td>20/06/08</td>
            <td>バグ修正</td>
            <td>
                <ul>
                    <li>
                        「Ruins」ドロップメニューの変更に伴って、ページをスクロールした状態でRuinsメニューを見ようとすると
                        メニューが上へ移動するバグを発見。修正
                    </li>
                    <li>スマホ用アイコン設定が消失していた為、修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/07</td>
            <td>専用ページ</td>
            <td>
                <ul>
                    <li>今月1日に公開した開発計画ページのみPDFにしていたが、Webページ表示へ変更</li>
                    <li>トップページの協賛欄の表示を変更</li>
                    <li>「www.eriel.net」からもリダイレクトするよう再設定したが失敗</li>
                    <li>上部メニューにあった「About」は開設当時から設置していましたが、以降機能を持たせることはなかったので削除</li>
                    <li>「Ruins」ドロップメニューの横幅サイズを変更</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/04</td>
            <td>トップページの更新</td>
            <td>
                <ul>
                    <li>
                        .htaccessの設定変更により、トップページのURLを「https://eriel.net/top」ではなく
                        「https://eriel.net」に省略するようにした。Chromeからは「eriel.net」のドメインのみの表示へ変更
                    </li>
                    <li>トップページURL変更に伴い、利用規約内の推奨リンクURLを変更</li>
                    <li>
                        セキュリティの向上を目的に「http://eriel.net/~」でのアクセスを暗号化した「https://eriel.net/」へ
                        自動で切り替わる仕様に変更
                    </li>
                    <li>榿木原遺跡ページのタイトル名が「福王子古墳群」になっていた誤表記を修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/06/01</td>
            <td>計画</td>
            <td>
                <ul>
                    <li>今後の開発計画を公開</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/24</td>
            <td>削除</td>
            <td>
                <ul>
                    <li>1都3県の緊急事態宣言解除検討に伴い、COVID-19に関するコンテンツを削除</li>
                    <li>.htaccess設定の見直しを検討</li>
                    <li>GitHubにサイトデータを公開することを決定</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/19</td>
            <td>プライバシー</td>
            <td>
                <ul>
                    <li>プライバシーページを作成</li>
                    <li>史跡ドロップメニューが画面縦幅が狭いと、全部見えなかったバグを修正</li>
                    <li>設定画面から現在の閲覧デバイスが何か表示する機能を追加</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/18</td>
            <td>更新</td>
            <td>
                <ul>
                    <li>緊急事態宣言解除に伴いトップページを更新</li>
                    <li>マップデータが完成した史跡ページを追加。内容は手付かず</li>
                    <li>Googleアナリティクス導入に伴いCookie規約を更新</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/17</td>
            <td>開発環境の再編成</td>
            <td>
                <ul>
                    <li>当サイトのGit管理を検討</li>
                    <li>Googleアナリティクス導入</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/15</td>
            <td>個人情報保護方針</td>
            <td>
                <ul>
                    <li>個人情報に関する方針追加を示唆</li>
                    <li>フォルダ構造、ナビバー関連の表示を修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/13</td>
            <td>修正と追加</td>
            <td>
                <ul>
                    <li>ナビバー関連の表示部を部分的に修正</li>
                    <li>利用規約、Cookie規約を追加</li>
                    <li>上記に伴い、Cookieの仕様を一部変更(domain,secure)</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/12</td>
            <td>構造変更</td>
            <td>
                <ul>
                    <!--ソースコード上部にコピー防止メッセージを追加。基本はユーザの性善説-->
                    <li>ナビバー関連の処理機構を変更</li>
                    <li>大伴古墳群、榿木原遺跡に関するトピックを部分的に修正。一部モザイクも修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/11</td>
            <td>コンテンツの追加</td>
            <td>
                <ul>
                    <li>榿木原遺跡に関するトピックを追加</li>
                    <li>大伴古墳群に関するトピックを追加</li>
                    <li>ナビバー関連の処理構造の変更を検討</li>
                    <!--<li>近江神宮裏山古墳群に関するトピックも追加</li>-->
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/10</td>
            <td>トラフィック対策</td>
            <td>
                <ul>
                    <li>史跡ページで大量の画像を読み込んでしまうトラフィック過多問題を最小限に抑えるよう修正</li>
                    <li>元サイズ画像と縮小画像の2パターンを用意した</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/09</td>
            <td>ユーザビリティ向上</td>
            <td>
                <ul>
                    <li><b uk-tooltip="なんどくかんじ">難読漢字</b>にカーソルを添えると（スマホ、タブレットの場合はタップ）読み仮名を表示するテスト機能を追加</li>
                    <li>トップページのスライド画面をどの端末からでも画面いっぱいに表示するよう修正</li>
                    <li>詳細内の史跡タブが全体的に左寄りになっていたのを修正</li>
                    <li>
                        開設当初のページがGoogleのキャッシュに残ってしまい、リンクするとtop.htmlのサイトにアクセスしてしまう不具合を発見。(現在は404エラーが出る)Googleに削除申請をした
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/08</td>
            <td>地図と写真</td>
            <td>
                <ul>
                    <li>史跡ページの基礎が完成『概要』『所在地』『詳細』</li>
                    <li>概要はその史跡の大まかな説明をする</li>
                    <li>所在地はGoogleMyMapで紹介することに決定した</li>
                    <li>詳細はその史跡の写真に特化したページで構成することに決定</li>
                    <li>このページ(新着情報)をスマホから見るとテーブルが大きく型崩れしていたので修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/07</td>
            <td>構造変更</td>
            <td>
                <ul>
                    <li>サイト全体の処理構造を変更</li>
                    <li>Cookieにバグがあったので修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/06</td>
            <td>細かな修正</td>
            <td>
                <ul>
                    <li>全体的に見ずらい要素やバグを修正</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/05</td>
            <td>ブラックテーマ</td>
            <td>
                <ul>
                    <li>サイトのテーマ切替を実装</li>
                    <li>新型コロナウイルス(COVID-19)に関する注意喚起を作成(期間限定)</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/04</td>
            <td>サイドメニュー</td>
            <td>
                <ul>
                    <li>スマホ/タブレット用メニューを開発</li>
                    <li>開発当時はリンク先は未定</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/03</td>
            <td>hi,PHP!</td>
            <td>
                <ul>
                    <li>HTMLからPHPへソースコードを大幅変更</li>
                    <li>より拡張性の高いサイト構築の一歩を踏み出した</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/02</td>
            <td>ロゴ</td>
            <td>
                <ul>
                    <li>サイト名を「古代大津史」へ戻す。以降このタイトル名で運営している</li>
                    <li>ファビコンを作成したが、色合いが地味になってしまった為に棄却</li>
                    <li>作成したアイコンは、現在サイトのロゴマークとして利用されている</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/05/01</td>
            <td>サイト名</td>
            <td>
                <ul>
                    <li>サイト名を『(仮)古代大津史』に変更</li>
                    <li>サイトアイコンの作成を決定。実行に移した</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/04/30</td>
            <td>エラー対策</td>
            <td>
                <ul>
                    <li>.htaccessを設定</li>
                    <li>拡張子を隠蔽</li>
                    <li>サイト名を『(仮)大津考古学』に変更。この頃サイト名が迷走していた</li>
                    <li>一時は『大津考古学』で表示されていた</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>20/04/29</td>
            <td>開設</td>
            <td>
                <ul>
                    <li>ドメインを取得</li>
                    <li>Webサイトを開設</li>
                    <li>開設当時のサイト名は『古代大津史』</li>
                </ul>
            </td>
        </tr>
        <!--
        <tr>
            <td>20/04/28</td>
            <td>PHPフレームワーク</td>
            <td>
            ドメイン名を仮決定した。この時点で後にPHPを利用することは決めており、
            PHPフレームワークをLaravelか、MediaPediaか悩んだが結論は、そもそもそこまで
            高レベルなものを開発する予定がなかったため、使用しないことを選択
            </td>
        </tr>
        <tr>
            <td>20/04/27</td>
            <td>レンタルサーバー</td>
            <td>Webサーバーに詳しい友人にお勧めレンタルサーバーを教わった。この時はまだ何を題材にサイト開設するかはまだ未定でした</td>
        </tr>
        <tr>
            <td>20/04/21</td>
            <td>CSS</td>
            <td>
            当時流行りのCSSフレームワーク「UIKit」の存在を知る。フロントエンドフレームワークについては、Bootstrap4にて
            お世話になったことがあるが、よりモダンさに惹かれたことでサイト方針の１つであるモダンな歴史サイトに決めた。
            </td>
        </tr>
        <tr>
            <td>20/04/18</td>
            <td>最初</td>
            <td>Webサイト開発を交友関係を持つ知人に対し仄めかす</td>
        </tr>
        -->
        </tbody>
    </table>
</div>
<!--フッター-->
<?php include $_ENV['ROOT']."include/footer.php" ?>